spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cosmo_cats
    username: cosmo
    password: cats
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8089/oauth2/jwks

security:
  api:
    key: super-secret-key
